version: 2
updates:
  - package-ecosystem: gradle
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 99

  - package-ecosystem: gradle
    directory: "/million-dollar-idea-core"
    schedule:
      interval: daily
    open-pull-requests-limit: 99

  - package-ecosystem: npm
    directory: "/million-dollar-idea-ui"
    schedule:
      interval: daily
    open-pull-requests-limit: 99

  - package-ecosystem: github-actions
    directory: "/.github"
    schedule:
      interval: daily
    open-pull-requests-limit: 99
