name: build ogreg-public

on:
  workflow_dispatch:
    paths:
      - "million-dollar-idea-ui/**" # Only run if only a UI file has changed
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  build:
    name: Build Typescript
    runs-on: ubuntu-latest

  steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build
        working-directory: ./million-dollar-idea-ui # Make sure we run our UI commands in the UI directory
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm run build
