name: build ogreg-public

on:
  workflow_dispatch:
    paths:
      - "million-dollar-idea-ui/**" # Only run if only a UI file has changed
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  build:
    name: Build Typescript
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Using Node ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: npm install
        working-directory: ./million-dollar-idea-ui
        run: npm install

      - name: Install Angular CLI
        run: npm install -g @angular/cli

      - name: Verify Angular CLI installation
        run: ng version

      - name: Build
        working-directory: ./million-dollar-idea-ui
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm run build

      - name: Build And Deploy
        working-directory: ./million-dollar-idea-ui
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_ZEALOUS_STONE_08CA4AB10 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "/" # App source code path
          api_location: "" # Api source code path - optional
          output_location: "dist/angular-basic" # Built app content directory - optional
          ###### End of Repository/Build Configurations ######
