name: Build Java

on:
  workflow_dispatch:
    paths-ignore:
      - "million-dollar-idea-ui/**" # Don't run if only a UI file has changed

jobs:
  build:
    name: Build Java
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Using JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'zulu'
          cache: maven
      - name: Build with Maven
        run: mvn -B package --file ./million-dollar-idea-core/pom.xml
