name: build ogreg-public

on:
  workflow_dispatch:
    paths:
      - "million-dollar-idea-ui/**" # Only run if only a UI file has changed
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  build:
    name: Build Typescript
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Using Node ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache NPM packages
        uses: actions/cache@v2.1.4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install Angular CLI
        run: npm install -g @angular/cli

      - name: Verify Angular CLI installation
        run: ng version

      - name: Build
        working-directory: ./million-dollar-idea-ui # Make sure we run our UI commands in the UI directory
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm run build
